🔧 Add imports order rule
gads-citron/eslint-config-citron pull request #16
Opened 2022-04-13 16:11 UTC by XavierGuilloton

2022-04-20 04:45 UTC, tgerboui requested changes

2022-04-20 04:45 UTC, tgerboui commented on index.js
> +      'error',
`warning` for now, this is not obligation for me.
See to set `error` in another major version.

2022-04-20 04:45 UTC, tgerboui commented on index.js
> +    // Order import with line separation between groups
Ajouter aussi de la doc dans le README.

2022-04-20 04:45 UTC, tgerboui commented on index.js
> +    // Order import with line separation between groups
Add also documentation in `README.md`.

2022-04-20 04:45 UTC, tgerboui commented on index.js
> +        // Add module import (@Module) after external import
Do not relate to business logic (`module`) here, module is only sensfull in some projects.

2022-04-20 04:45 UTC, tgerboui commented on index.js
> +            pattern: '@*',
Be careful here with this pattern.
Some package like for example `@nestjs/common` use '@' at begining which is not a locale directory.

Maybe target just only local file if possbile of new line required.(also regular import)

2022-04-20 05:08 UTC, tgerboui commented
And I had many strange errors when testing this import rule, did you try it ?

Errors like this when I have only one local import :
<img width="558" alt="Screenshot 2022-04-19 at 19 07 49" src="https://user-images.githubusercontent.com/17905436/164154629-99a1b196-32b5-4508-8aea-4eee03fe8013.png">

2023-10-20 13:06 UTC, wayglem commented
Closing as this is too old

2023-10-20 13:06 UTC, closed without merging